In [1]:
import numpy as np

In [3]:
x = np.array([[1 , 2], [3 , 4]])
y = np.array([[1 , 2], [3 , 4]])

In [5]:
np.add(x,y)

array([[2, 4],
       [6, 8]])

In [6]:
np.subtract(x,y)

array([[0, 0],
       [0, 0]])

In [7]:
np.multiply(x,y)

array([[ 1,  4],
       [ 9, 16]])

In [8]:
np.linalg.inv(x)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [9]:
np.transpose(x)

array([[1, 3],
       [2, 4]])

In [25]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [21]:
np.diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [30]:
np.full((3,3),69)

array([[69, 69, 69],
       [69, 69, 69],
       [69, 69, 69]])